version: "3"
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: local-web
    restart: always
    volumes:
      - ./client/:/app
      - /app/node_modules/
      - /app/.next
    ports:
      - 3000:3000
  db:
    image: mysql
    restart: always
    container_name: local-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    container_name: local-adminer
    ports:
      - 3080:8080
