version: "3"
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./client/:/app
      - /app/node_modules/
      - /app/.next
    ports:
      - 3000:3000
